name: Android Build & Deploy
 
on:
 workflow_dispatch:
 
jobs:
 deploy:
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: ./android
  steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v1
    with:
      node-version: "16.x"

  - name: Install npm dependencies
    run: npm install
    working-directory: ./

  - name: Set up ruby env
    uses: ruby/setup-ruby@v1
    with:
      ruby-version: 2.7.2
      bundler-cache: true

  - name: Run tests
    run: bundle exec fastlane test

  - name: Decode Service Account Key JSON File
    uses: timheuer/base64-to-file@v1
    id: service_account_json_file
    with:
      fileName: "serviceAccount.json"
      encodedString: ${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON }}

  - name: Decode Keystore File
    uses: timheuer/base64-to-file@v1
    id: android_keystore
    with:
      fileName: "android_keystore.keystore"
      encodedString: ${{ secrets.KEYSTORE_FILE }}

  - name: Define version code with offset
    env:
        RUN_NUMBER: ${{ github.run_number }}
        INITIAL_VERSION_CODE: 73
    run: |
        VERSION_CODE=$((INITIAL_VERSION_CODE + RUN_NUMBER))
        echo "version_code=$VERSION_CODE" >> $GITHUB_ENV

  - name: Update version code
    uses: chkfung/android-version-actions@v1.1
    with:
      gradlePath: android/app/build.gradle
      versionCode: ${{ env.version_code }}

  - name: Build & deploy Android release
    run: bundle exec fastlane deploy
    env:
      KEYSTORE_FILE: ${{ steps.android_keystore.outputs.filePath }}
      STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS}}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      ANDROID_JSON_KEY_FILE: ${{ steps.service_account_json_file.outputs.filePath }}

  - name: Upload build artifacts
    uses: actions/upload-artifact@v2
    with:
      name: assets
      path: |
        ${{ github.workspace }}/android/app/build/outputs/bundle/release
